name: Full Stack Deploy v4 (Infra + App)

on:
  push:
    branches: [ main ]

jobs:
  terraform-infra:
    name: '1. Terraform Infrastructure'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

  build-and-deploy-app:
    name: '2. Build and Deploy App'
    needs: terraform-infra # Espera a que la infraestructura exista
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Construcción para AMD64 para evitar el Exec Format Error
      - name: Build & Push Docker v4
        run: |
          az acr login --name acrcarlos69v4
          docker buildx build \
            --platform linux/amd64 \
            -t acrcarlos69v4.azurecr.io/it-support-app:v4 \
            ./app-js --push

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group RG-Laboratorio20-v4 --name aks-lab-v4 --overwrite-existing

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f app-js/deploy.yaml
          kubectl apply -f app-js/ingress.yaml
          
      - name: Force Rollout
        run: |
          kubectl rollout restart deployment it-support-deployment-v4