name: "V3: Infrastructure & App Deployment"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-and-deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      # ==========================================
      # 1. TERRAFORM: INFRAESTRUCTURA
      # ==========================================
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      # ==========================================
      # 2. AZURE LOGIN & ACR PUSH
      # ==========================================
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build & Push Docker Image
        run: |
          az acr login --name acrcarlos69v3
          docker build -t acrcarlos69v3.azurecr.io/it-support-app:v3 .
          docker push acrcarlos69v3.azurecr.io/it-support-app:v3

      # ==========================================
      # 3. KUBERNETES DEPLOYMENT
      # ==========================================
      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: 'RG-Laboratorio20-v3'
          cluster-name: 'aks-lab-v3'

      - name: Deploy a Kubernetes
        run: |
          # Aplicamos los YAML de la carpeta app-js
          kubectl apply -f app-js/ingress.yaml
          kubectl apply -f app-js/deploy.yaml
          
          # Forzamos actualización para que use la imagen :v3 recién subida
          kubectl set image deployment/it-support-deployment it-support-app=acrcarlos69v3.azurecr.io/it-support-app:v3
          
          # Reinicio para limpiar cualquier error 404 previo en caché del Pod
          kubectl rollout restart deployment/it-support-deployment

      - name: Verificar Estado Final
        run: |
          kubectl get pods
          kubectl get svc -A
          kubectl get ingress