apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-support-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: it-support-app
  template:
    metadata:
      labels:
        app: it-support-app
    spec:
      containers:
      - name: it-support-app
        image: acrcarlos69v3.azurecr.io/it-support-app:v4
        ports:
        - containerPort: 3000
        env:
        - name: DB_USER
          value: "sqladmin"
        - name: DB_PASSWORD
          value: "Password1234!"
        - name: DB_SERVER
          value: "sqlserver-carlos-v3.database.windows.net"
        - name: DB_NAME
          value: "ticketsdb-v3"
---
apiVersion: v1
kind: Service
metadata:
  name: it-support-service
spec:
  selector:
    app: it-support-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP