apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: it-support-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # Esto asegura que si llamas a /tickets, el pod reciba /tickets
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: it-support-service
            port:
              number: 80